"""
Django settings for vixx_trader project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import environ

from pathlib import Path


env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ABI_DIR  = lambda app: os.path.join(BASE_DIR, app, "contracts\\compiled\\abi.json")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#s6v5&k^$$9y_3(pd_^@my0)9hvdxqhx3=cg)30y1c0ka4n6yd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio_manage.apps.PortfolioManageConfig',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vixx_trader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vixx_trader.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

WALLET = {
    'PRIMARY_PUBLIC_KEY':    env('PRIMARY_PUBLIC_KEY'),
    'PRIMARY_PRIVATE_KEY':   env('PRIMARY_PRIVATE_KEY'),
    'SECONDARY_PUBLIC_KEY':  env('SECONDARY_PUBLIC_KEY'),
    'SECONDARY_PRIVATE_KEY': env('SECONDARY_PRIVATE_KEY'),
    'HARDHAT_1_PUBLIC_KEY':  env('HARDHAT_1_PUBLIC_KEY'),
    'HARDHAT_1_PRIVATE_KEY': env('HARDHAT_1_PRIVATE_KEY'),
    'HARDHAT_2_PUBLIC_KEY':  env('HARDHAT_2_PUBLIC_KEY'),
    'HARDHAT_2_PRIVATE_KEY': env('HARDHAT_2_PRIVATE_KEY'),
    'GANACHE_1_PUBLIC_KEY':  env('GANACHE_1_PUBLIC_KEY'),
    'GANACHE_1_PRIVATE_KEY': env('GANACHE_1_PRIVATE_KEY'),
    'GANACHE_2_PUBLIC_KEY':  env('GANACHE_2_PUBLIC_KEY'),
    'GANACHE_2_PRIVATE_KEY': env('GANACHE_2_PRIVATE_KEY'),
}

CONTRACT = {
    'ALCHEMY_URL_KEY': env('ALCHEMY_URL_KEY'),
    'SMART_CONTRACT_ADDRESS': env('SMART_CONTRACT_ADDRESS'),
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
