# Generated by Django 3.1.2 on 2021-11-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64, unique=True)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('balance', models.FloatField(default=0.0)),
                ('coin_count', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_executed', models.DateTimeField()),
                ('coin_count', models.FloatField(default=0.0)),
                ('coin_cost', models.FloatField(default=0.0)),
                ('purchase_currency', models.CharField(default='USD', max_length=5)),
                ('message', models.CharField(default='', max_length=35)),
            ],
        ),
    ]
