# Generated by Django 3.1.2 on 2021-11-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='portfolio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio_manage.portfolio'),
            preserve_default=False,
        ),
    ]
