# Generated by Django 3.1.2 on 2021-11-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manage', '0003_auto_20211122_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.CharField(default='', max_length=16),
        ),
    ]
